# docker-compose.yml

version: "3.4"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    command: npm run dev
    ports:
      - 3000:3000
    volumes:
      - .:/app
